Repository data-engineering-team4/kpop_dashboard, pull requests merged in 2023-06, with the labels that each got.

#26 Feat/#19
  Dockerfile
  Dockerfile-selenium
  dags/operators/upload_files_to_s3_operator.py
  dags/spotify_regional_weekly_chart.py
  docker-compose.yaml
  requirements.txt
Labels: enhancement

#31 Feat/#3
  Dockerfile-selenium
  dags/scrape_reddit_kpop_posts_dag.py
  requirements.txt
Labels: enhancement

#29 Feat/#19
  dags/operators/delete_files_operator.py
  dags/operators/upload_files_to_s3_operator.py
  dags/spotify_country_weekly_chart.py
  dags/spotify_global_weekly_chart.py
  dags/utils.py
  docker-compose.yaml
Labels: bug, enhancement

#30 Feature/#17
  .gitignore
  dags/kpop_artist_album_track_extraction.py
  dags/utils/aws_util.py
  dags/utils/spotify_util.py
  requirements.txt
Labels: enhancement, invalid

#32 Utils 정리, dbt 초기 환경설정
  dags/spotify_country_weekly_chart.py
  dags/spotify_global_weekly_chart.py
  dags/utils.py
  dags/utils/common_utils.py
  dags/utils/spotify_util.py
  dbt/dbt_project.yml
  dbt/profiles.yml
Labels: enhancement

#34 Feat # 12
  dags/kpop_artist_album_track_extraction_dag.py
  dags/sql/album.sql
  dags/sql/artist.sql
  dags/sql/track.sql
  dags/utils.py
  docker-compose.yaml
  requirements.txt
Labels: enhancement

#35 Feat/#33
  .gitignore
  dags/config/country_weekly_chart.py
  dags/sql_test.py
  dags/utils/common_utils.py
  docker-compose.yaml
  requirements.txt
Labels: enhancement
